name: gauge_flutter_app
description: An Assessment Management System (AMS).

dependencies:
  flutter:
    sdk: flutter
  json_annotation: "^0.2.3"
  http_client: "^0.3.1"
  oauth2: "^1.2.0"
  cupertino_icons: "^0.1.0"
  flutter_webview_plugin: "^0.1.5"

dev_dependencies:
  build_runner: "^0.8.2+2"
  json_serializable: "^0.5.0"
  flutter_launcher_icons: "^0.2.0"
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/canvas-developer-key.json

# Used by the flutter_launcher_icons library
flutter_icons:
  image_path: "assets/gauge_logo.png"
  android: true
  ios: 'GaugeIcon'